server:
  port: ${SERVER_PORT}

spring:
  application:
    name: discovery
  cloud:
    config:
      uri: http://localhost:9000
      username: confUser
      password: confPassword
    discovery:
        enabled: true

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      # credentials to access eureka server in environment variables : http://discUser:discPassword@localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"